apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  namespace: avalara-tests
spec:
  replicas: 3
  selector:
    matchLabels:
      name: blue-pod
  template:
    metadata:
      labels:
        name: blue-pod
    spec:
      containers:
      - name: blue-pod
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080
